#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Vérifications de pré-commit pour AfriCart..."

# 1. Le Linter 
echo " Nettoyage du code (Lint)..."
npm run lint -- --fix || exit 1

# 2. La logique des types 
echo "Vérification TypeScript..."
npx tsc --noEmit || exit 1

# 3. Les Tests (S'assurer que rien n'est cassé)
# echo "Exécution des tests unitaires..."
# npm test || exit 1

# 4. Sécurité (Vérification seule)
echo "Vérification des vulnérabilités..."
npm audit || echo "Des vulnérabilités ont été trouvées. Pense à faire 'npm audit fix' manuellement."

echo "Prêt pour le commit !"